"""initial schema

Revision ID: 8dbcbf70f366
Revises: 
Create Date: 2026-06-23 14:31:19.905716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbcbf70f366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geo_fence', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor_plan_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_i18n', sa.JSON(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('exhibit_order', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exhibits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('dynasty', sa.String(length=100), nullable=True),
    sa.Column('location_hint', sa.String(length=200), nullable=True),
    sa.Column('plan_x', sa.Float(), nullable=True),
    sa.Column('plan_y', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exhibit_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('proposed_floor_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_heading', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ),
    sa.ForeignKeyConstraint(['proposed_floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exhibit_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(length=100), nullable=False),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exhibit_id'], ['exhibits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narrations')
    op.drop_table('feedbacks')
    op.drop_table('exhibit_images')
    op.drop_table('chat_sessions')
    op.drop_table('exhibits')
    op.drop_table('routes')
    op.drop_table('floors')
    op.drop_table('museums')
    # ### end Alembic commands ###
