"""collect tracking

Revision ID: dcc06e533c92
Revises: 8dbcbf70f366
Create Date: 2026-06-26 13:33:44.977868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc06e533c92'
down_revision: Union[str, Sequence[str], None] = '8dbcbf70f366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('museum_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collect_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['collect_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exhibit_images', sa.Column('source_ref', sa.String(length=500), nullable=True))
    op.add_column('exhibit_images', sa.Column('content_hash', sa.String(length=100), nullable=True))
    op.add_column('exhibit_images', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    op.add_column('exhibits', sa.Column('source_ref', sa.String(length=500), nullable=True))
    op.add_column('exhibits', sa.Column('content_hash', sa.String(length=100), nullable=True))
    op.add_column('exhibits', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    op.add_column('museums', sa.Column('source_ref', sa.String(length=500), nullable=True))
    op.add_column('museums', sa.Column('content_hash', sa.String(length=100), nullable=True))
    op.add_column('museums', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    op.add_column('narrations', sa.Column('content_hash', sa.String(length=100), nullable=True))
    op.add_column('narrations', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('narrations', 'fetched_at')
    op.drop_column('narrations', 'content_hash')
    op.drop_column('museums', 'fetched_at')
    op.drop_column('museums', 'content_hash')
    op.drop_column('museums', 'source_ref')
    op.drop_column('exhibits', 'fetched_at')
    op.drop_column('exhibits', 'content_hash')
    op.drop_column('exhibits', 'source_ref')
    op.drop_column('exhibit_images', 'fetched_at')
    op.drop_column('exhibit_images', 'content_hash')
    op.drop_column('exhibit_images', 'source_ref')
    op.drop_table('collect_items')
    op.drop_table('collect_jobs')
    # ### end Alembic commands ###
